//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace RegistroATM.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class VisitaEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto VisitaEntities usando la cadena de conexión encontrada en la sección 'VisitaEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public VisitaEntities() : base("name=VisitaEntities", "VisitaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto VisitaEntities.
        /// </summary>
        public VisitaEntities(string connectionString) : base(connectionString, "VisitaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto VisitaEntities.
        /// </summary>
        public VisitaEntities(EntityConnection connection) : base(connection, "VisitaEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Visita> Visita
        {
            get
            {
                if ((_Visita == null))
                {
                    _Visita = base.CreateObjectSet<Visita>("Visita");
                }
                return _Visita;
            }
        }
        private ObjectSet<Visita> _Visita;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Visita. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVisita(Visita visita)
        {
            base.AddObject("Visita", visita);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="VisitaModel", Name="Visita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visita : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Visita.
        /// </summary>
        /// <param name="iD_Visita">Valor inicial de la propiedad ID_Visita.</param>
        public static Visita CreateVisita(global::System.Int32 iD_Visita)
        {
            Visita visita = new Visita();
            visita.ID_Visita = iD_Visita;
            return visita;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID_Visita
        {
            get
            {
                return _ID_Visita;
            }
            set
            {
                if (_ID_Visita != value)
                {
                    OnID_VisitaChanging(value);
                    ReportPropertyChanging("ID_Visita");
                    _ID_Visita = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID_Visita");
                    OnID_VisitaChanged();
                }
            }
        }
        private global::System.Int32 _ID_Visita;
        partial void OnID_VisitaChanging(global::System.Int32 value);
        partial void OnID_VisitaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> HoraInicio
        {
            get
            {
                return _HoraInicio;
            }
            set
            {
                OnHoraInicioChanging(value);
                ReportPropertyChanging("HoraInicio");
                _HoraInicio = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraInicio");
                OnHoraInicioChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _HoraInicio;
        partial void OnHoraInicioChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHoraInicioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.TimeSpan> HoraFin
        {
            get
            {
                return _HoraFin;
            }
            set
            {
                OnHoraFinChanging(value);
                ReportPropertyChanging("HoraFin");
                _HoraFin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HoraFin");
                OnHoraFinChanged();
            }
        }
        private Nullable<global::System.TimeSpan> _HoraFin;
        partial void OnHoraFinChanging(Nullable<global::System.TimeSpan> value);
        partial void OnHoraFinChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ATM
        {
            get
            {
                return _ATM;
            }
            set
            {
                OnATMChanging(value);
                ReportPropertyChanging("ATM");
                _ATM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ATM");
                OnATMChanged();
            }
        }
        private Nullable<global::System.Int32> _ATM;
        partial void OnATMChanging(Nullable<global::System.Int32> value);
        partial void OnATMChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NombreTecnico
        {
            get
            {
                return _NombreTecnico;
            }
            set
            {
                OnNombreTecnicoChanging(value);
                ReportPropertyChanging("NombreTecnico");
                _NombreTecnico = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NombreTecnico");
                OnNombreTecnicoChanged();
            }
        }
        private global::System.String _NombreTecnico;
        partial void OnNombreTecnicoChanging(global::System.String value);
        partial void OnNombreTecnicoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusInicial
        {
            get
            {
                return _EstatusInicial;
            }
            set
            {
                OnEstatusInicialChanging(value);
                ReportPropertyChanging("EstatusInicial");
                _EstatusInicial = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusInicial");
                OnEstatusInicialChanged();
            }
        }
        private global::System.String _EstatusInicial;
        partial void OnEstatusInicialChanging(global::System.String value);
        partial void OnEstatusInicialChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String EstatusFinal
        {
            get
            {
                return _EstatusFinal;
            }
            set
            {
                OnEstatusFinalChanging(value);
                ReportPropertyChanging("EstatusFinal");
                _EstatusFinal = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("EstatusFinal");
                OnEstatusFinalChanged();
            }
        }
        private global::System.String _EstatusFinal;
        partial void OnEstatusFinalChanging(global::System.String value);
        partial void OnEstatusFinalChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FotoMenu
        {
            get
            {
                return _FotoMenu;
            }
            set
            {
                OnFotoMenuChanging(value);
                ReportPropertyChanging("FotoMenu");
                _FotoMenu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FotoMenu");
                OnFotoMenuChanged();
            }
        }
        private global::System.String _FotoMenu;
        partial void OnFotoMenuChanging(global::System.String value);
        partial void OnFotoMenuChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FotoVoucher
        {
            get
            {
                return _FotoVoucher;
            }
            set
            {
                OnFotoVoucherChanging(value);
                ReportPropertyChanging("FotoVoucher");
                _FotoVoucher = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FotoVoucher");
                OnFotoVoucherChanged();
            }
        }
        private global::System.String _FotoVoucher;
        partial void OnFotoVoucherChanging(global::System.String value);
        partial void OnFotoVoucherChanged();

        #endregion

    
    }

    #endregion

    
}
